import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:returnit/models/item_model.dart';
import 'package:returnit/models/user_model.dart';
import 'package:returnit/models/request_model.dart';
import 'package:returnit/models/notification_model.dart';

class TestDbPage extends StatefulWidget {
  const TestDbPage({super.key});

  @override
  State<TestDbPage> createState() => _TestDbPageState();
}

class _TestDbPageState extends State<TestDbPage> {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  String _status = '';

  void _setStatus(String msg) {
    setState(() => _status = msg);
  }

  Future<void> _createTestUser() async {
    try {
      final user = UserModel(
        id: 'test_user_001',
        email: 'test@example.com',
        name: 'Test Student',
        phoneNumber: '1234567890',
        role: 'user',
      );
      await _firestore.collection('users').doc(user.id).set(user.toMap());
      _setStatus('User created: ${user.name}');
    } catch (e) {
      _setStatus('Error creating user: $e');
    }
  }

  // Random Data Sources
  final List<String> _titles = [
    'Keys', 'Wallet', 'Blue Bag', 'Laptop', 'Water Bottle', 
    'Phone Charger', 'Calculus Textbook', 'Headphones', 'Umbrella'
  ];
  
  final List<String> _locations = [
    'مبنى مدني', 
    'مبنى الورش', 
    'مبنى عمارة'
  ];

  String _getRandomElement(List<String> list) {
    return list[DateTime.now().microsecond % list.length];
  }

  Future<void> _createTestItem({String type = 'lost'}) async {
    try {
      final randomTitle = _getRandomElement(_titles);
      final randomLocation = _getRandomElement(_locations);
      final randomResolved = DateTime.now().microsecond % 5 == 0; // 20% chance of being resolved

      final item = ItemModel(
        id: '', // Generated by Firestore
        title: '$randomTitle (${DateTime.now().second})',
        description: 'Random generated item for testing.',
        location: randomLocation,
        userId: 'test_user_001',
        imageUrl: 'https://placehold.co/600x400/png',
        type: type,
        category: 'Electronics',
        timestamp: DateTime.now(),
        isResolved: randomResolved,
      );
      await _firestore.collection('items').add(item.toMap());
      _setStatus('Created $type item: ${item.title} at ${item.location}');
    } catch (e) {
      _setStatus('Error creating item: $e');
    }
  }

  Future<void> _createTestRequest() async {
    try {
      final request = RequestModel(
        id: '',
        itemId: 'some_item_id',
        requesterId: 'test_user_002',
        ownerId: 'test_user_001',
        status: 'pending',
        timestamp: DateTime.now(),
      );
      await _firestore.collection('requests').add(request.toMap());
      _setStatus('Request created by: ${request.requesterId}');
    } catch (e) {
      _setStatus('Error creating request: $e');
    }
  }

  Future<void> _createTestNotification() async {
    try {
      final notif = NotificationModel(
        id: '',
        userId: 'test_user_001',
        title: 'Item Match Found',
        body: 'We found a match for your lost keys!',
        timestamp: DateTime.now(),
        isRead: false,
      );
      await _firestore.collection('notifications').add(notif.toMap());
      _setStatus('Notification created for: ${notif.userId}');
    } catch (e) {
      _setStatus('Error creating notification: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('DB Tester')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text('Status: $_status', style: const TextStyle(fontWeight: FontWeight.bold)),
            const Divider(),
            ElevatedButton(
              onPressed: _createTestUser,
              child: const Text('Create Test User (users)'),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: () => _createTestItem(type: 'lost'),
              style: ElevatedButton.styleFrom(backgroundColor: Colors.blue, foregroundColor: Colors.white),
              child: const Text('Create Random LOST Item'),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: () => _createTestItem(type: 'found'),
               style: ElevatedButton.styleFrom(backgroundColor: Colors.orange, foregroundColor: Colors.white),
              child: const Text('Create Random FOUND Item'),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: _createTestRequest,
              child: const Text('Create Test Request (requests)'),
            ),
             const SizedBox(height: 8),
            ElevatedButton(
              onPressed: _createTestNotification,
              child: const Text('Create Test Notification (notifications)'),
            ),
          ],
        ),
      ),
    );
  }
}
