// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBt0Ha0CjiSYOekm2v9ynYgtuF7ThIgQ',
    appId: '1:555189403404:web:7e05ae7ae2cf6bad3e1329',
    messagingSenderId: '555189403404',
    projectId: 'return-it-d9eae',
    authDomain: 'return-it-d9eae.firebaseapp.com',
    storageBucket: 'return-it-d9eae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4T77pCinmEb0C8DCUM_2KduppEjVOFak',
    appId: '1:555189403404:android:3d4a4ae4748dd1a63e1329',
    messagingSenderId: '555189403404',
    projectId: 'return-it-d9eae',
    storageBucket: 'return-it-d9eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhk9vDkmiQ8vdnOn07SJSjZZEmHjXQp8k',
    appId: '1:555189403404:ios:3d30c71aa94432c53e1329',
    messagingSenderId: '555189403404',
    projectId: 'return-it-d9eae',
    storageBucket: 'return-it-d9eae.firebasestorage.app',
    iosBundleId: 'com.example.returnit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhk9vDkmiQ8vdnOn07SJSjZZEmHjXQp8k',
    appId: '1:555189403404:ios:3d30c71aa94432c53e1329',
    messagingSenderId: '555189403404',
    projectId: 'return-it-d9eae',
    storageBucket: 'return-it-d9eae.firebasestorage.app',
    iosBundleId: 'com.example.returnit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbBt0Ha0CjiSYOekm2v9ynYgtuF7ThIgQ',
    appId: '1:555189403404:web:a578943cfbfc18713e1329',
    messagingSenderId: '555189403404',
    projectId: 'return-it-d9eae',
    authDomain: 'return-it-d9eae.firebaseapp.com',
    storageBucket: 'return-it-d9eae.firebasestorage.app',
  );
}
