import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:returnit/models/item_model.dart';
import 'package:returnit/models/request_model.dart';
import 'package:returnit/models/user_model.dart';
import 'package:intl/intl.dart';

class ItemDetailsPage extends StatefulWidget {
  const ItemDetailsPage({super.key});

  @override
  State<ItemDetailsPage> createState() => _ItemDetailsPageState();
}

class _ItemDetailsPageState extends State<ItemDetailsPage> {
  bool _isLoading = false;
  final User? currentUser = FirebaseAuth.instance.currentUser;
  late Future<UserModel?> _ownerFuture;
  bool _futureInitialized = false;

  // --- Actions ---

  Future<void> _createRequest(ItemModel item) async {
    if (currentUser == null) return;

    setState(() => _isLoading = true);

    try {
      final request = RequestModel(
        id: '', // Generated by Firestore
        itemId: item.id,
        requesterId: currentUser!.uid,
        ownerId: item.userId,
        status: 'pending',
        timestamp: DateTime.now(),
      );

      await FirebaseFirestore.instance
          .collection('requests')
          .add(request.toMap());

      // Create Notification for the Owner
      final notificationRef =
          FirebaseFirestore.instance.collection('notifications').doc();
      await notificationRef.set({
        'id': notificationRef.id,
        'userId': item.userId, // Notify the Item Owner
        'title': 'New Request',
        'body': 'Someone requested your item: "${item.title}"',
        'timestamp': FieldValue.serverTimestamp(),
        'isRead': false,
        'relatedItemId': item.id,
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Request sent successfully!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating request: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _deleteItem(ItemModel item) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Item'),
        content: const Text(
            'Are you sure you want to delete this item? This action cannot be undone.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirm != true) return;

    setState(() => _isLoading = true);

    try {
      await FirebaseFirestore.instance
          .collection('items')
          .doc(item.id)
          .delete();
      if (mounted) {
        Navigator.pop(context); // Go back to items list
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Item deleted successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error deleting item: $e')),
        );
        setState(() => _isLoading = false);
      }
    }
  }

  void _navigateToRequests() {
    Navigator.pushNamed(context, '/requests');
  }

  Future<UserModel?> _fetchOwner(String userId) async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(userId)
          .get();
      if (doc.exists) {
        return UserModel.fromMap(doc.data() as Map<String, dynamic>);
      }
    } catch (e) {
      debugPrint('Error fetching owner: $e');
    }
    return null;
  }

  // --- UI Builders ---

  @override
  Widget build(BuildContext context) {
    final item = ModalRoute.of(context)!.settings.arguments as ItemModel;
    final isOwner = currentUser?.uid == item.userId;

    // Initialize fetching owner once
    if (!_futureInitialized) {
      _ownerFuture = _fetchOwner(item.userId);
      _futureInitialized = true;
    }

    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(
        children: [
          // Background Image (Full height behind) or Top Section
          Positioned(
            top: 0,
            left: 0,
            right: 0,
            height: MediaQuery.of(context).size.height * 0.45,
            child: item.imageUrl != null && item.imageUrl!.isNotEmpty
                ? Image.network(
                    item.imageUrl!,
                    fit: BoxFit.cover,
                    errorBuilder: (_, __, ___) => Container(
                      color:
                          const Color(0xFFD89B56), // Fallback color from design
                      child: const Center(
                          child: Icon(Icons.broken_image,
                              size: 64, color: Colors.white54)),
                    ),
                  )
                : Container(
                    color: const Color(0xFFD89B56), // Mockup backdrop color
                    child: const Center(
                        child:
                            Icon(Icons.image, size: 64, color: Colors.white54)),
                  ),
          ),

          // Back Button
          Positioned(
            top: MediaQuery.of(context).padding.top + 10,
            left: 16,
            child: GestureDetector(
                onTap: () => Navigator.pop(context),
                child: CircleAvatar(
                  backgroundColor: Colors.black26,
                  child: const Icon(Icons.arrow_back, color: Colors.white),
                )),
          ),

          // Content Sheet
          Positioned(
            top: MediaQuery.of(context).size.height * 0.4,
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.vertical(top: Radius.circular(30)),
              ),
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Title and Status Badge
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          child: Text(
                            item.title,
                            style: const TextStyle(
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0D1B2A),
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 16, vertical: 8),
                          decoration: BoxDecoration(
                            color: item.isResolved
                                ? const Color(0xFFE8F5E9)
                                : const Color(0xFFE3F2FD),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          child: Text(
                            item.isResolved ? 'Claimed' : 'Unclaimed',
                            style: TextStyle(
                              color: item.isResolved
                                  ? Colors.green
                                  : const Color(0xFF2196F3),
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),

                    // Badge/Category text
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 12, vertical: 6),
                      decoration: BoxDecoration(
                        color: Colors.grey[200],
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        item.category,
                        style: TextStyle(
                          color: Colors.grey[800],
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),

                    // Description
                    Text(
                      item.description,
                      style: TextStyle(
                        fontSize: 14,
                        color: Colors.grey[600],
                        height: 1.6,
                      ),
                    ),
                    const SizedBox(height: 24),

                    Divider(color: Colors.grey[300]),
                    const SizedBox(height: 16),

                    // Date Reported
                    _buildInfoRow(
                      icon: Icons.calendar_today,
                      title: 'Date Reported',
                      value: DateFormat.yMMMMd().format(item.timestamp),
                    ),
                    const SizedBox(height: 16),

                    // Location
                    _buildInfoRow(
                      icon: Icons.location_on,
                      title: 'Location',
                      value: item.location,
                    ),
                    const SizedBox(height: 24),

                    Divider(color: Colors.grey[300]),
                    const SizedBox(height: 16),

                    // Posted By User
                    FutureBuilder<UserModel?>(
                      future: _ownerFuture,
                      builder: (context, snapshot) {
                        final user = snapshot.data;
                        final name = user?.name ?? 'Loading...';
                        final userImage = user?.profileImageUrl;

                        return Row(
                          children: [
                            CircleAvatar(
                              radius: 24,
                              backgroundColor: Colors.grey[300],
                              backgroundImage:
                                  userImage != null && userImage.isNotEmpty
                                      ? NetworkImage(userImage)
                                      : null,
                              child: (userImage == null || userImage.isEmpty)
                                  ? const Icon(Icons.person, color: Colors.grey)
                                  : null,
                            ),
                            const SizedBox(width: 12),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Posted by',
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Colors.grey[500],
                                  ),
                                ),
                                Text(
                                  name,
                                  style: const TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                    color: Color(0xFF0D1B2A),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        );
                      },
                    ),
                    const SizedBox(height: 40),

                    // Action Buttons
                    if (isOwner)
                      _buildOwnerActions(context, item)
                    else
                      _buildViewerActions(context, item),

                    // Extra spacing for bottom
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
          ),

          // Loading Overlay
          if (_isLoading)
            Container(
              color: Colors.black45,
              child: const Center(child: CircularProgressIndicator()),
            ),
        ],
      ),
    );
  }

  Widget _buildInfoRow(
      {required IconData icon, required String title, required String value}) {
    return Row(
      children: [
        Container(
          width: 48,
          height: 48,
          decoration: BoxDecoration(
            color: const Color(0xFFE8F1F5), // Light blue-grey background
            borderRadius: BorderRadius.circular(12),
          ),
          child: Icon(icon, color: const Color(0xFF4A5568), size: 24),
        ),
        const SizedBox(width: 16),
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[500],
              ),
            ),
            const SizedBox(height: 4),
            Text(
              value,
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Color(0xFF0D1B2A),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildOwnerActions(BuildContext context, ItemModel item) {
    return Column(
      children: [
        // Wide "Requests" Button
        SizedBox(
          width: double.infinity,
          height: 56,
          child: ElevatedButton(
            onPressed: _navigateToRequests,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFFE8EAF6), // Light indigo/blue
              elevation: 0,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
            ),
            child: const Text(
              'Requests',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
                color: Color(0xFF1A1A1A),
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            Expanded(
              child: SizedBox(
                height: 56,
                child: ElevatedButton(
                  onPressed: () {
                    // Navigate to the appropriate edit screen based on item type
                    if (item.type == 'lost') {
                      Navigator.pushNamed(
                        context,
                        '/report_lost',
                        arguments: item,
                      );
                    } else {
                      Navigator.pushNamed(
                        context,
                        '/report_found',
                        arguments: item,
                      );
                    }
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFE8EAF6),
                    elevation: 0,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                  ),
                  child: const Text('Edit',
                      style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                          color: Color(0xFF1A1A1A))),
                ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: SizedBox(
                height: 56,
                child: ElevatedButton(
                  onPressed: () => _deleteItem(item),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFEF5350), // Red
                    elevation: 0,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                  ),
                  child: const Text('Delete',
                      style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                          color: Colors.white)),
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildViewerActions(BuildContext context, ItemModel item) {
    final String mainButtonText =
        item.type == 'lost' ? 'I Found It' : "It's Mine";

    return Row(
      children: [
        Expanded(
          flex: 3,
          child: SizedBox(
            height: 56,
            child: ElevatedButton(
              onPressed: () => _createRequest(item),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFE8EAF6),
                elevation: 0,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: Text(
                mainButtonText,
                style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                    color: Color(0xFF1A1A1A)),
              ),
            ),
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          flex: 2,
          child: SizedBox(
            height: 56,
            child: OutlinedButton(
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Contact feature coming soon!')),
                );
              },
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFF1A1A1A), width: 1.5),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
              child: const Text('Contact',
                  style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                      color: Color(0xFF1A1A1A))),
            ),
          ),
        ),
      ],
    );
  }
}
